import type { Metadata } from "next";
import {  DM_Serif_Text, } from "next/font/google";
import "./globals.scss";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const serifText = DM_Serif_Text({
 weight: ['400'],
 subsets: ['latin']
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={serifText.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
