import type { Metadata } from "next";
import {   Mea_Culpa, Waterfall, Roboto } from "next/font/google";
import "./globals.scss";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const roboto = Roboto({
 weight: ['400'],
 subsets: ['latin'],
 variable: '--roboto'
});

const waterfall = Waterfall({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--waterfall'
 });

const meaCulpa = Mea_Culpa({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--culpa'
})


//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${meaCulpa.variable} ${waterfall.variable}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
